# Generated by Django 4.2.1 on 2023-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guias', '0003_cargas_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes',
            name='abrev_fwr',
            field=models.CharField(db_column='Abreviatura:', max_length=6),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='cotizador_fwr',
            field=models.CharField(blank=True, db_column='Cotizaciones:', max_length=64),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='ctc_fwr',
            field=models.TextField(db_column='Informacion extra:'),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='manager_fwr',
            field=models.CharField(blank=True, db_column='Agentes de Cuenta:', max_length=64),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='nombre_fwr',
            field=models.CharField(db_column='Nombre de Agente:', max_length=64),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='operativo_fwe',
            field=models.CharField(blank=True, db_column='Operativo Aereos:', max_length=64),
        ),
    ]
