# Generated by Django 4.2.1 on 2023-05-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guias', '0004_alter_agentes_abrev_fwr_alter_agentes_cotizador_fwr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargas',
            name='abrev_fwr',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='bultos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='hawb',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='peso',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='volumen',
            field=models.FloatField(blank=True),
        ),
    ]
