# Generated by Django 4.2.1 on 2023-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guias', '0005_alter_cargas_abrev_fwr_alter_cargas_bultos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargas',
            name='abrev_fwr',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='ata',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='atd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='bultos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='cotizacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='estado',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargas',
            name='volumen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
